### ISSUE TITLE
"What about watchdog?"

### ISSUE THREAD

**Issue by hreuver0183** [rgleason/watchdog_pi#108]
I saw the question without any context. So I assumed you wanted the watchdog-pi to be tested with debian bookworm/intel i7 (iarch64).
Long story short: the plugin compiles, but it also just installs from the pluginmanager upstream.
I checked quickly and the plugin seemed to work. Perhaps there was an issue which has already beeb fixed?

If there was a specific open issue I can check, otherwise I'll close this issue soon.

**Comment by rgleason** [comment]
Thanks.  I guess we're all set. Except there are a number of Issues with alarms....
