### ISSUE TITLE
Alerting via discord and sending anchorage position even if not an alert

### ISSUE THREAD

**Issue by Ch1nkara** [rgleason/watchdog_pi#113]
Hi @rgleason, 
I was willing to contribute to the watchdog plugin to add a few features that I would love to use myself.
Before doing a MR, I wanted to know if you would be interested in it.

Here is an example I had in mind for my needs, featuring John and his wife wanting to monitor their sailboat anchorage while going ashore:
```Text
Prerequisite: John's phone stays onboard, sharing its internet connexion to opencpn.

John would give a discord webhook to opencpn via the watchdog plugin and
 select alerting via discord. 

He would also give another discord webhook as the "information to discord".

Now while on shore, John and his wife would be alerted if the anchor is dragging. 

On the "information to discord" conversation, watchdog would publish the position of 
the boat reatively to the anchoring point every 15 minutes (duration could be set in the plugin)
```

I haven't dig into the technical stuff yet but I believe it is feasible and that I could code that. I wanted to make sure you were ok with such features before trying to implement them.
What are your thoughts on the matter ?

**Comment by Ch1nkara** [comment]
I found a simpler way to achieve that without touching the plugin source code:
- for alerting via discord, i use a script and the "command" option (similar to the email example in the documentation)
- for info status, i use anydesk between opencpn and a smartphone to check on the boat whenever i want

**Comment by rgleason** [comment]
Would you be willing to write this up in more detail and post here?

**Comment by Ch1nkara** [comment]
@rgleason, sorry for the late answer, here is the setup I'm successfully using:
 - On my personal discord account, I created a server named after my sailboat. In this server, I created 2 channels, "anchorage-infos" and "anchorage-alarms". Notifications from "anchorage-infos" are muted. I receive notifications on my smartphone when a message i posted on "anchorage-alarms"
 - On the server, I created 2 webhooks that allow me to send messages to these chanels from scripts
 - In addition, i registered to www.callmebot.com in order to be able to receive a telegram call from a script (only free solution i found to receive a phone call)

Finally, whenever we go ashore, my wife leave her phone onboard, sharing it's internet connection to the raspberry pi running opencpn. Before leaving:
 1. I run the following script from the terminal so that i receive a screenshot of opencpn every 5 minutes on discord channel "anchorage-infos": (this allows me to keep an eye of the boat during our trip ashore)
```bash
#!/bin/bash

while true; do

  #Remove old screenshot and take a new one
  rm screenshot.jpg 2>/dev/null
  scrot screenshot.jpg

  #Send the screenshot to discord channel "anchorage-infos"
  curl -F "file1=@screenshot.jpg" \
     -F "payload_json={\"content\": \"Message from MY-AWESOME-SHIP, screenshot\"}" \
     'https://discord.com/api/webhooks/endOfWebhookURL'

  sleep 300
done
```

2. I setup Watchdog to trigger the following script as an anchorage script alarm:
```bash
#!/bin/bash

#Call via telegram with text to speech message
curl -G 'http://api.callmebot.com/start.php?source=web&user=@MY-TELEGRAM-USERNAME&lang=en-US-Standard-B' --data-urlencode \
"text=Message from MY-AWESOME-SHIP, anchor is dragging"

#Post a message to discord channel "anchorage-alarms"
curl -H "Content-Type: application/json" \
     -X POST \
     -d "{\"content\": \"Message from MY-AWESOME-SHIP, anchor is dragging\"}" \
     'https://discord.com/api/webhooks/endOfWebhookURL'
```

If it's still unclear let me know. 
In the end, I dropped anydesk because when i wrote the previous message, the tests i ran where on a raspberry pi 32bits. But Openplotter is running on 64bits raspberry OS, which anydesk do not support, as of today
