### ISSUE TITLE
out of this plugin issue

### ISSUE THREAD

**Issue by filochard** [rgleason/watchdog_pi#25]
Hi Rick
I open an issue here because there is no way to open an issue inside your oesenc_pi repository
There is something missing in the CMakeLists.txt file of the oesenc_pi code (no ability to install closed source binary and library for arm architectures)
I have a patch to propose to complete this CMakeLists.txt (written by Barry Jackson, a skilled Mageia packager)

May you create a possiblity to submit issues  inside your oesenc_pi repository
Or do you wish I send you this patch elsewhere

**Comment by rgleason** [comment]
@filochard 
Are you wishing to direct this to @bdbcat about oesenc_pi?

You should post this under  https://github.com/bdbcat/oesenc_pi
Issues   that is the main repos.

https://github.com/bdbcat/oesenc_pi/issues

Look at the structure, of forks, it gives some idea.... the Icon after  "Fork" on the right side.
https://github.com/bdbcat/oesenc_pi/network/members

**Comment by rgleason** [comment]
Thanks, closing

**Comment by filochard** [comment]
Sorry 
I used your repo to build oesenc version 4.2.15 and thought that was the only one we can use since it include the last modification of README.md

Besides this we can't cmake_build from the git clone 4.2.19 version from bdbcat 
whose the last tagged version is 4.0.10

**Comment by bdbcat** [comment]
"Besides this we can't cmake_build from the git clone 4.2.19 version from bdbcat
whose the last tagged version is 4.0.10"
Will you post an issue with details on the bdbcat github repo?
Thanks
Dave

**Comment by filochard** [comment]
Ok
I will

**Comment by filochard** [comment]
Done
https://github.com/bdbcat/oesenc_pi/issues/119
Thanks
