### ISSUE TITLE
Watchdog still probes old version of pypilot

### ISSUE THREAD

**Issue by marcobergman** [rgleason/watchdog_pi#33]
Please merge the august 26th commit 7f7c655 from seandepagnier; this commit upgrades the watchdog for modern versions of pypilot. Without this, it cannot connect to pypilot:
![image](https://user-images.githubusercontent.com/17980560/147477322-4e526d1c-28dc-4fb4-b940-eee9a813bd65.png)

**Comment by rgleason** [comment]
Thanks, was not aware of this.  Will do, but remind me if I forget....please.

**Comment by marcobergman** [comment]
No worries - keep up the good work! Much appreciated.

**Comment by rgleason** [comment]
Pypilot Alarm has been removed from Watchdog now

**Comment by marcobergman** [comment]
Must say, that was not my intention.

**Comment by rgleason** [comment]
Yes, but it is my intention, and not your fault at all.  Please see https://github.com/rgleason/watchdog_pi/issues/40

Very Sorry about this. If you want it, you could fork my version and make a PR that actually works for Pypilot Alarm and I will very gladly accept it.

I don't have the skill or the time to fix this and have tried many  x's to get my repos aligned with Sean's,,, (not too much interest there)  and I am finished with trying that.

**Comment by rgleason** [comment]
PS:  I left the remnants of the Pypilot Alarm in the code, just commented out. However Sean's version does some disastrous things like deleting files that are needed, then adding new files with a different name, etc. which then merge with all kinds of conflicts no matter what I try to do. It is a mess I don't want to get into.

**Comment by marcobergman** [comment]
Thx for your response, I understand now. I don't qualify to attempt such a modification so I will leave it at this.
