### ISSUE TITLE
New location for master sources?

### ISSUE THREAD

**Issue by pa2wlt** [rgleason/watchdog_pi#34]
Hi

Good to see you managed to get the CircleCI build for MacOSx up and running. Compliments and thx!
I was doing the same thing and ran into the issues that you solved already. :-)
It would have been better to check out your fork, you'r quite ahead I see.
The tarball that is downloaded with OpenCPN 5.6.0, has been built via your your fork, right? (both changed on Dec 9, 2021).
Is this from now on than the new main source, to ask for pull request? Or is that still Sean's?
Hope to hear.

**Comment by rgleason** [comment]
I have been building Sean's plugins for multiple OS for years.  Sometimes he will accept a PR from me sometimes not.

**Comment by rgleason** [comment]
Can we close this now?
