### ISSUE TITLE
MACOSX_DEPLOYMENT_TARGET=10.9 vs 10.10

### ISSUE THREAD

**Issue by pa2wlt** [rgleason/watchdog_pi#35]
In circleci-build-macos.sh the variable MACOSX_DEPLOYMENT_TARGET is set to 10.9. Whereas @bdbcat Dave indicated here: https://opencpn.org/flyspray/index.php?do=editcomment&task_id=2726&id=7702 MACOSX_DEPLOYMENT_TARGET should be 10.10.

Not sure if this is an issue (since the tarball works), though it maybe better to be consistent. :-)

**Comment by rgleason** [comment]
Can we close this?
