### ISSUE TITLE
antora.yml: syntax errors, manual excluded from main

### ISSUE THREAD

**Issue by leamas** [rgleason/watchdog_pi#37]
The watchdog manual cannot be included in the main manual due to syntax errors reported in https://github.com/opencpn-manuals/main/runs/5883888217.

I have removed watchdog from the Plugin Manual to make it build until antora.yml is fixed

**Comment by rgleason** [comment]
Close?

**Comment by leamas** [comment]
Yes. 

Note that I don't remove any plugin manuals unless they actually make the overall build fail.  It's  now back again.
