### ISSUE TITLE
Feet selection does not work

### ISSUE THREAD

**Issue by rgleason** [rgleason/watchdog_pi#47]
Feet does not work. Edit menu is in meters, when feet is selected it goes back to meters.

**Comment by rgleason** [comment]
Search "feet" (4 hits in 4 files of 17 searched)
  C:\Users\fcgle\source\watchdog_pi\src\Alarm.cpp (1 hit)
	Line 1090:     enum Units { METERS, FEET } m_Units;
  C:\Users\fcgle\source\watchdog_pi\src\WatchdogUI - Copy.cpp (1 hit)
	Line  994: 	wxString m_cUnitsChoices[] = { _("Meters"), _("Feet") };
  C:\Users\fcgle\source\watchdog_pi\src\WatchdogUI.cpp (1 hit)
	Line  996: 	wxString m_cUnitsChoices[] = { _("Meters"), _("Feet") };
  C:\Users\fcgle\source\watchdog_pi\src\WatchdogUI.cpp.bak (1 hit)
	Line  994: 	wxString m_cUnitsChoices[] = { _("Meters"), _("Feet") };

**Comment by rgleason** [comment]
Search "METERS" (10 hits in 4 files of 17 searched)
  C:\Users\fcgle\source\watchdog_pi\src\Alarm.cpp (4 hits)
	Line  165:         anchordist *= 1853.248; /* in meters */
	Line 1082:         return m_depth * (m_iUnits == METERS ? 1 : 3.281);
	Line 1086:         return m_depthrate * (m_iUnits == METERS ? 1 : 3.281);
	Line 1090:     enum Units { METERS, FEET } m_Units;
  C:\Users\fcgle\source\watchdog_pi\src\WatchdogUI - Copy.cpp (2 hits)
	Line  496: 	m_staticText39 = new wxStaticText( this, wxID_ANY, _("meters"), wxDefaultPosition, wxDefaultSize, 0 );
	Line  994: 	wxString m_cUnitsChoices[] = { _("Meters"), _("Feet") };
  C:\Users\fcgle\source\watchdog_pi\src\WatchdogUI.cpp (2 hits)
	Line  498: 	m_staticText39 = new wxStaticText( this, wxID_ANY, _("meters"), wxDefaultPosition, wxDefaultSize, 0 );
	Line  996: 	wxString m_cUnitsChoices[] = { _("Meters"), _("Feet") };
  C:\Users\fcgle\source\watchdog_pi\src\WatchdogUI.cpp.bak (2 hits)
	Line  496: 	m_staticText39 = new wxStaticText( this, wxID_ANY, _("meters"), wxDefaultPosition, wxDefaultSize, 0 );
	Line  994: 	wxString m_cUnitsChoices[] = { _("Meters"), _("Feet") };
Search "feet" (4 hits in 4 files of 17 searched)

**Comment by bdbcat** [comment]
Rick...
I am ready to make a PR in branch "update2" correcting faults.
Is this the branch currently being used for Production?  If so, I recommend that you merge it to master (AFTER ACCEPTING MY NEXT PR), just to remove all chances of confusion.
One can never quite remember what was the objective of an ambiguously named branch like "update2".  Where is "update1?  Will there be an "update3"?

**Comment by bdbcat** [comment]
Aside...  The error had nothing to do with the NMEA library.  Please drop consideration of NMEA library update on watchdog.  It is a real distraction, and does not gain us anything.

**Comment by rgleason** [comment]
Ok, I will drop nmea.  I am just like a dog with a bone.

Update2 was used because I already had an update branch. 
However the right branch to use is master.  I moved your PR's into that 4 days ago.  Sorry.
I can I intend to make a PR to master and clean the whole mess up

I intend to remove all the other branches after this.
Thanks.

**Comment by rgleason** [comment]
The field was  "protected"  rather than "public" 
https://github.com/rgleason/watchdog_pi/commit/859ef6ebcecba296ad9635d150da8028aaf264bc
