### ISSUE TITLE
RFE  Update the nmea library

### ISSUE THREAD

**Issue by rgleason** [rgleason/watchdog_pi#50]
I've made a new branch "nmea-lib" which has in it an exact copy of what Opencpn uses now for the nmea library.

https://github.com/rgleason/watchdog_pi/tree/nmea-lib

I have tried to build it but it fails, and have traced the errors down in [watchdog-new-errors-nmealib.txt.](https://github.com/rgleason/watchdog_pi/blob/nmea-lib/watchdog-new-errors-nmealib.txt)
They are for the following parameters Mda Mta Dpt and Rsa

Would very much like to get this fixed so that redog can test it on Tuesday when he is on his boat.
https://www.cruisersforum.com/forums/f134/opencpn-version-5-8-4-released-276788.html#post3808312
and Corsair can test depth
https://www.cruisersforum.com/forums/f134/watchdog-plugin-150313.html

If anyone can help by advising how to fix these 4 errors or by making a PR, it would be much appreciated.

@bdbcat  @jongough @transmitterdan @Hakansv

**Comment by bdbcat** [comment]
https://www.cruisersforum.com/forums/f134/watchdog-plugin-150313-115.html#post3808414

**Comment by bdbcat** [comment]
What are the exact failures in watchdog NMEA processing?
With a clear list, I'll make PRs tonight to correct them in watchdog, without a wholesale upgrade of NMEA library.

**Comment by rgleason** [comment]
Do you mean the errors found when building, when using the current WD version of nmea0183?

They're are none because it builds. However it does not appear that depth data is getting to the alarm.  Why? because in the Depth Alarm Edit window, when I turn on "Alert if no data"  The depth alarm immediately becomes red. When I turn it off it immediately goes black.

**Comment by bdbcat** [comment]
Do you have a sample VDR file that shows the error?

**Comment by rgleason** [comment]
![Depth-old](https://github.com/rgleason/watchdog_pi/assets/2363959/8ee01dfa-9117-4da6-bd42-b2330875d9a3)
![Depth-new](https://github.com/rgleason/watchdog_pi/assets/2363959/9d22e3a3-7c63-40f5-b937-0504205fb8ae)
[depth-new-DPT.txt](https://github.com/rgleason/watchdog_pi/files/12268450/depth-new-DPT.txt)
[depth-old-DPT.txt](https://github.com/rgleason/watchdog_pi/files/12268451/depth-old-DPT.txt)

If you rename  lib/nmea  to lib/nmea-O  and lib/nmea-old to lib/nmea  you'll have the original set.

**Comment by rgleason** [comment]
CF Post  https://www.cruisersforum.com/forums/f134/watchdog-plugin-150313.html#post3808752

**Comment by rgleason** [comment]
N branch nmea-lib https://github.com/rgleason/watchdog_pi/tree/nmea-lib

**Comment by rgleason** [comment]
Dave, thanks.   ...while you are fixing it, can you get "feet" selection working?  It always seems to go back to meters.

**Comment by Hakansv** [comment]
Rick...
If you copy dpt.cpp from Dashboard to Watchdog I think the NMEA0183 version >= 3.0 will be covered as well.
I my local case:
Copy from Dashboard: C:\Builds\...........\OpenCPN\plugins\dashboard_pi\src\nmea0183\dpt.cpp
Paste to Watchdog: C:\Builds\...........\watchdog_pi\libs\nmea0183\src\dpt.cpp

**Comment by rgleason** [comment]
Thanks Hakan, I will keep that in mind. Dave has found some other sources of the problem and the short and long versions of dpt seem to be working right now.  I should have thought of that, I tried taking nmea from OpenCPN, but O does not handle depth at all.....!!!

Of course that would have to change if we had a route checker for depth and obstructions....

**Comment by rgleason** [comment]
PS, will be adding a new watchdog version 1.0.259.0 that Dave has fixed

**Comment by rgleason** [comment]
It was not the nmea library at all. Closing

**Comment by Hakansv** [comment]
With the dpt.cpp from Dashboard I've successfully run the files you attached above. Also the dpt version 3 messages.

**Comment by rgleason** [comment]
Humm, maybe I should just copy it over and  build watchdog again?  But perhaps Dave already did this? I will compare the dpt files.  Dave recently told me the nmea files are a red herring....

**Comment by rgleason** [comment]
dpt.cpp has a conditional for nmea 3
dpt.hpp is the same.
dbt.cpp is the same.
dbt.hpp matches.

**Comment by rgleason** [comment]
Have done a winmerge compare and am finding that the differences are mostly small formatting.
I have corrected a number of them so the upper half is matching.
Will go through it tonight.

![Screenshot (1610)](https://github.com/rgleason/watchdog_pi/assets/2363959/b835aa2e-f023-44cd-a731-934b469ff5d7)
![Screenshot (1609)](https://github.com/rgleason/watchdog_pi/assets/2363959/aee50c31-adf9-47d8-b516-24cfc9378633)

**Comment by rgleason** [comment]
Hakan,
After going through all of the files there are really only two files that are substantially different, the rest of the differences were largely very minor format issues such as an extra line or a line that is very slightly different with an extra space, etc.
I am enclosing the watchdog versions of mda.cpp and mda.hpp

**MDA.cpp**  Line 62 and 99 is different

**Dashboard has**
   Pressure = 0.0;
   UnitOfMeasurement.Empty();
   AirTemp = 999.0;     <----Line 62

**Watchdog has**
   Pressure = 0.0;
   UnitOfMeasurement.Empty();
   RelativeHumidity = 0.0;    <----Line 62

**MDA.hpp** 

Dashboard has
     double  Pressure, AirTemp;
      wxString UnitOfMeasurement;
      blank                                  <---- Line 58

Watchdog has
      double  Pressure, AirTemp;
      wxString UnitOfMeasurement;
      double RelativeHumidity;    <---- Line 58

How would you suggest I handle these differences?  See attached files from watchdog.
I am trying to get this plugin compiled and out as I am leaving tomorrow. unfortunately.

[mda.cpp.txt](https://github.com/rgleason/watchdog_pi/files/12270741/mda.cpp.txt)
[mda.hpp.txt](https://github.com/rgleason/watchdog_pi/files/12270744/mda.hpp.txt)

The Watchdog nmea set was also missing xte.cpp so I just copied it as I could imagine there being a need for an xte alarm.
