### ISSUE TITLE
Bad interaction with o-chart plugin

### ISSUE THREAD

**Issue by Corsair-63** [rgleason/watchdog_pi#64]
Since I Installed in my boat the latest Watchdog plugin I have a problem with o-Charts update.

```
Windows 11 Pro ARM64 ver 22H2 22621.2215
OCPN 5.8.4-0+1637c28
o-chart plugin 2.0.0.64
Watchdog plugin 2.4.70.0
```

If I have active the mini window of Watchdog plugin when click on "Update chart List" button the windows remains as attached with no more progress, and when click on any part of the screen it just beeps but nothing else.
![sshot-3](https://github.com/rgleason/watchdog_pi/assets/76228638/73a9d9d1-7f28-4865-8dc1-1506f80dbb33)
as far as I see OCPN is working in the background but can't do anything else.

if Watchdog mini window is closed the check of update process charts is done properly.

log file attached.
[opencpn.log.zip.pdf](https://github.com/rgleason/watchdog_pi/files/12578483/opencpn.log.zip.pdf)

**Comment by rgleason** [comment]
All I can say is don't do that. I never do that. I close all plugins and  do  o-Charts update.
Updating charts is serious business consuming lots of computer power.
You must not expect to multitask while doing chart operations.
All I can say is I never do that.

You want to capture or download faxes at the same time you are downloading charts? Crazy.

**Comment by Corsair-63** [comment]
I'd never had such behavior in other computers with OCPN installed, only I can figure is that that one is not so powerful with only 8GB but my Surface with ARM processor and 16GB and my previous tiny computer now at home with intel and 8GB, I can do any task at the same time with no problem.
and I've done the o-chats update with previous version of WD in the same computer without any problem, this has happened from some days ago only.
Also, I tested tonight with tablet and computer at home and there has not been any issue, the update has done straight away.

**Comment by rgleason** [comment]
Why not just remove Watchdog and make sure you are correct about Watchdog?
If you still have trouble with charts ... then focus on the real problem.

**Comment by rgleason** [comment]
Ok Carmelo,  perhaps this can be closed now, and reopened when you have a more definitive problem?  Usually the OP closes these.

**Comment by Corsair-63** [comment]
Agreed as I cannot reproduce by now, thanks for the time
