### ISSUE TITLE
Test Bugs Corsair

### ISSUE THREAD

**Issue by rgleason** [rgleason/watchdog_pi#67]
https://www.cruisersforum.com/forums/f134/watchdog-plugin-150313.html

Tested on board version WD 2.4.73.0

Windows 11 Pro ARM64 Spanish, latest patch Sep 12, 2023

same behavior as [desktop](https://www.cruisersforum.com/forums/tags/desktop.html) at home, tested with all devices enable only Echo-sounder tested one by one.

    not able to set [wind](https://www.cruisersforum.com/forums/tags/wind.html) as True apparent neither True absolute.
    again, disappeared the [depth](https://www.cruisersforum.com/forums/tags/depth.html) reading while is dashboard is shown, attached three screenshots one with ES 0183 > Off > ES N2k. showing the [alarm](https://www.cruisersforum.com/forums/tags/alarm.html) and dashboard showing the correct reading.
    course not able to set the course reading when click on actual course, always set to COG.

attached log file with the only input from UDP and set in OCPN the priority of signals.

![WD_No_ES](https://github.com/rgleason/watchdog_pi/assets/2363959/eda5880e-fbaf-497e-8dae-14fb63893a6d)
![WD_ES0183](https://github.com/rgleason/watchdog_pi/assets/2363959/67494b66-5929-4a46-8877-36925f491d0c)
![WD_ESN2K](https://github.com/rgleason/watchdog_pi/assets/2363959/0eed7bf5-c025-4e2e-b894-7b353fc82233)
[Test_WD24730.txt](https://github.com/rgleason/watchdog_pi/files/12614460/Test_WD24730.txt)

**Comment by Corsair-63** [comment]
re-tested today on board with the NMEA 0183 Echo-sounder only and set to:
- ver 1.5, WD and dashboard losses the reading.
- ver 2.0, WD no reading and Dashboard reads correct depth.
- ver 3.0, WD no reading and Dashboard reads correct depth.

**Comment by rgleason** [comment]
Corsair, thank you for your excellent reporting and carry through. It is much appreciated. If you notice anything else about WD please advise, via the same media.and process.  Good job.

Since you are the OP (original poster) it is normally you that should close this Issue. Ok?

**Comment by Corsair-63** [comment]
I cannot close it, because the original one was done by you from mine in OCPN forum.
I've tried but not able to close it.
