### ISSUE TITLE
Bug: Not correct notation of new version

### ISSUE THREAD

**Issue by Corsair-63** [rgleason/watchdog_pi#69]
something strange from WD 2.4.73.0

Windows 11 Pro x64 Spanish version.

new [installation](https://www.cruisersforum.com/forums/tags/installation.html) of OCPN, installed plugins except WD.

done an [import](https://www.cruisersforum.com/forums/tags/import.html) plugin of latest alpha WD 2.4.73, splash [screen](https://www.cruisersforum.com/forums/tags/screen.html) that could be installed now and done.
installed version 2.4.73, working displayed in the plugin tab, etc.

if I click on update plugins when the splash [screen](https://www.cruisersforum.com/forums/tags/screen.html) says that list updated the version shown in this tab exchanges to 2.4.70 ???????

![sshot-2](https://github.com/rgleason/watchdog_pi/assets/76228638/80a87de5-b648-46d9-b402-6d1e0f1131af)

I've uninstalled and done the procedure again, and same behavior. after click on update list of plugins version exchange to 2.4.70 that has never been installed in this computer.

**Comment by Corsair-63** [comment]
superseded by: "https://github.com/rgleason/watchdog_pi/issues/70"

**Comment by rgleason** [comment]
Oh, sorry Corsair, I did not realize you had reported this!  Good, move closing one of these reports, we try not to have duplicates. Sorry again.
