### ISSUE TITLE
Bug: Issue on version 2.4.106 (Wind T-A Alarm) -fixed?

### ISSUE THREAD

**Issue by Corsair-63** [rgleason/watchdog_pi#74]
Windows 11 Pro ARM64 ver 22631.2506
OCPN 5.9.0-0
Watchdog 2.4.101.2

Wind alarm: 
- still not able to set as True Relative/Absolute
- sometimes the layout comes to confusion with the layout of alarm settings with direction/speed. attached screenshot.
- 
![sshot-8](https://github.com/rgleason/watchdog_pi/assets/76228638/63a4a0ca-8c33-4e04-8bb3-ae14009e5e1e)
![sshot-9](https://github.com/rgleason/watchdog_pi/assets/76228638/27cadf02-acf7-469d-86d5-e8a19fcc2d03)

**Comment by Corsair-63** [comment]
Windows 11 Pro ARM64 ver 22631.2861
OCPN 5.9.0-0+948.1ffe2ef
Watchdog 2.4.103

same behaviour with true wind, only followed Apparent.

**Comment by rgleason** [comment]
Same problem here https://github.com/rgleason/watchdog_pi/issues/88

**Comment by rgleason** [comment]
@Corsair-63 Carmelo, we really need a VDR file with a ".txt" extension, showing this specific problem. It is necessary to debug and test. Can you upload a file as " ____.txt" using drag and drop to this Issue? Thank you.

**Comment by Corsair-63** [comment]
Hi Rick,
tested on board and done a VDR file, also, left less NMEA data as possible and only left anemometer, GNSS and auto-pilot.

again, done the same procedure in WD:

- tested apparent, working.
- True relative, when setup it appears a random value in the speed and I have to exchange to desired alarm value of 25, done, and immediately the alarm triggers as there is no data.
- True Absolute, same than above.

not able to set the alarms in any case of True wind, and as you can see there are signal og GNSS and heading device too.

[WD_Wind.VDR.txt](https://github.com/rgleason/watchdog_pi/files/13918381/WD_Wind.VDR.txt)

**Comment by rgleason** [comment]
Corsair, please see the new version 2.4.105  pushed to  PIM
Hopefully this is fixed. We have Dave to thank for spending some time on it.

**Comment by Corsair-63** [comment]
for the reason I told I could not deeply test.

now true Relative it seems to work or at least is not giving me error or going to red.
true absolute becomes red as soon as activated.

as usual when exchanging from way of measuring relative to true relative either true absolute in the speed alarm setup appear one random number (maybe COG) but it doesn't keep the value of previous alarm.

**Comment by rgleason** [comment]
From[ the Manual](https://www.opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:opencpn_user_manual:advanced_features:nmea_sentences)
OR   [Opencpn Manual Basic PDF ](https://opencpn.org/wiki/dokuwiki/doku.php?id=opencpn:manual_basic:nmea0183&do=export_pdf)
OR  [Nmea Revealed](https://gpsd.gitlab.io/gpsd/NMEA.html)
[MWD - Wind Direction & Speed](https://gpsd.gitlab.io/gpsd/NMEA.html#_mwd_wind_direction_speed)
[MWV - Wind Speed and Angle](https://gpsd.gitlab.io/gpsd/NMEA.html#_mwv_wind_speed_and_angle)
[VWR - Relative Wind Speed and Angle](https://gpsd.gitlab.io/gpsd/NMEA.html#_vwr_relative_wind_speed_and_angle)
VWT - True Windspeed and Angle (obsolete)

**Comment by rgleason** [comment]
I've been trying to run this text file to test Wind T-A.
It contains all three wind types.  Used nmea checksum calculator above.

Wind T-A  True Absolute does not seem to be working.
If someone has another file that works, turning off and on the alert, please upload. Thanks.

[WD_Wind-T-A.txt](https://github.com/rgleason/watchdog_pi/files/14070458/WD_Wind-T-A.txt)
![Screenshot (1928)](https://github.com/rgleason/watchdog_pi/assets/2363959/67294e4f-8952-4b82-ad40-38bcd7514670)

**Comment by rgleason** [comment]
Closing, there is a duplicate.
