### ISSUE TITLE
Bug: Issue on version 2.4.101.2 (Weather Alarm)

### ISSUE THREAD

**Issue by Corsair-63** [rgleason/watchdog_pi#79]
Updated with latest version of WD 2.4.10.2
Windows 11 (23H2) x64 & ARM64 - O 5.9.0
recently purchased barometer & thermometer USB (Airduino Dongle v.5) to keep records of air pressure in OCPN.

first of all, I see one error in the watchdog manual, which could lead in operation error of the alarm: 
1 mBar = 1 hPa 
not that 
100 mBar = 1 hPa

never mind and I setup as per instructions and with proper values with same result.
I had to do some adjustments because this device doesn't work with latest CHM340/341 drivers 3.8.2023.2 so I had to revert to previous version 3.7.2022.1 and works like a charm.

weather device installed in COM8 and properly receiving data, also shown in Dashboard.

![sshot-3](https://github.com/rgleason/watchdog_pi/assets/76228638/17bda010-b44d-4215-83e3-85bd7fffc5b7)

could be seem that data is being received every two seconds.
I setup the alarm with rate value of **200 and 2 mbar** and every two or three seconds the alarms triggers  ?????
![sshot-2](https://github.com/rgleason/watchdog_pi/assets/76228638/ba6ab6a9-a0e7-4d00-8ecb-41d8a57a3c0f)

did I properly setup the alarm or is it a plugin error?

**Comment by Corsair-63** [comment]
going little bit deeper, started some test about it.
 
if uncheck "Alarm if no Data" there is no alarm.

started filtering data input:
1 - XDR sentences selected only, and no Temp displayed in OCPN Pressure seems not to work in WD (fixed in black).
2 - MTA selected only, and Temperature displayed in O and working Temp alarm in WD Pressure alarm not working.
3 - MDA selected only, Temp alarm not working and Pressure alarm working.
4 - MDA & MTA selected, Temp and Pressure Alarm working
5 - XDR & MTA selected, Temp Alarm working, Pressure alarm not.

what I read from NMEA documents MDA is a deprecated sentence since 2009 and MTA is not available since long time ago, all documented I've read recommend using XDR instead.

sample attached.
![sshot-1](https://github.com/rgleason/watchdog_pi/assets/76228638/92a0fd11-c73b-4bac-ba66-a8cd688d6ba6)

**Comment by rgleason** [comment]
To Fix
1.  Correct the error in the manual.  to  "1 mBar = 1 hPa"  rather than "100 mBar = 1 hPa"
2.  Use XDR snetences as shown above. MDA is deprecated and MTA is not available anymore.

**Comment by rgleason** [comment]
@Corsair-63   Carmelo, we really need a VDR file with a ".txt" extension, showing this specific problem.  It is necessary to debug and test. Can you upload a file as " ____.txt" using drag and drop to this Issue?  Thank you.

**Comment by Corsair-63** [comment]
Hi Rick,
I can reproduce this behaviour at home because I have available another same sensor for temperature and pressure together with Pixel and could check the data stream.

three files:

- Arduino_MTA_MDA.VDR.txt - Filtering as valid data MTA and MDA of Arduino
- Arduino_Only_XDR.VDR.txt - Filtering as valid data XDR of Arduino
- Pixel_Only_XDR.VDR.txt - Filtering as valid data XDR from Pixel only.

[Pixel_Only_XDR.VDR.txt](https://github.com/rgleason/watchdog_pi/files/13891571/Pixel_Only_XDR.VDR.txt)
[Arduino_MTA_MDA.VDR.txt](https://github.com/rgleason/watchdog_pi/files/13891572/Arduino_MTA_MDA.VDR.txt)
[Arduino_Only_XDR.VDR.txt](https://github.com/rgleason/watchdog_pi/files/13891573/Arduino_Only_XDR.VDR.txt)

now I'll explain the output in O, WD & Dashboard.
OCPN Version 5.9.0-0+1ffe2ef Build 2023-12-27
Windows 11 x64 23H2 22631.3007
WD 2.4.103

Arduino with XDR only  .......     WD    ......      Dashboard
Bar.................................................       No   ...........      No
Temp............................................        No   ...........      No
Pixel 8 with XDR only   
Bar................................................        No   ...........      Yes (?) supposed that the string of XDR from Pixel is the correct 
Temp............................................        No   ...........      No
Arduino with MTA & MDA only
Bar................................................        Yes   ...........      Yes 
Temp............................................        Yes   ...........      Yes

Yes: means displayed.
No: means doesn't display.

**Comment by rgleason** [comment]
The plugin has Humidity and Relative Humidity
![WD](https://github.com/rgleason/watchdog_pi/assets/2363959/e9821255-b49a-4583-a3ba-6552cbfcc5f0)

**Comment by Corsair-63** [comment]
Updated with latest version of WD 2.4.105
Windows 11 (23H2) x64 & ARM64 - O 5.9.0

Done the test at home with Arduino device.

in COM connection rejected MTA & MDA and accepted only XDR sentences.

WD correctly shows the values and alarms working.

really good, also Dashboard shows the pressure trends and value but not showing the temperature.
so, it means that Dashboard should not read the temperature value in XDR format.
in connection added to filter to accept MTA and now dashboard showing the temperature.

I guess that this thread is done for Watchdog.

**Comment by rgleason** [comment]
I am not so sure this is done.  Are you getting barameter readings and alarms?
Also what about Sea temp,  humidity and relative humidity?
Which file should I use on Windows?

**Comment by rgleason** [comment]
PS Hope your boat is ok.

**Comment by rgleason** [comment]
Fixed the manual  1 mBar = 1 hPa

**Comment by rgleason** [comment]
Corsair, do you have a file that has all the weather alarms?  That would be a huge help. I will keep it for testing.
Water temp
Sea water temp
Barometer
Relative Humidity
Humidity
...anything else environmental

**Comment by Corsair-63** [comment]
> Corsair, do you have a file that has all the weather alarms? That would be a huge help. I will keep it for testing. Dave will also use it I am sure.
> 
> * Water temp
> * Sea water temp
> * Humidity  (What is the difference?)
>   ...anything else environmental

FTB I couldn't make any test of parameter above, I have the vessel on shore, Sea water I can when I'll be floating again, I don't know when, relative humidity and humidity I have not available measure instrument to do so.

**Comment by Corsair-63** [comment]
> PS Hope your boat is ok. Let's make sure all the weather data works.

not really, and worst things is I'm not able to source the water ingress .😵‍💫

**Comment by rgleason** [comment]
I hope you can pump it dry.

**Comment by rgleason** [comment]
Barometer, Air Temp, Sea Temp and Humidity seem to be working. Closing.
