### ISSUE TITLE
Issue on version 2.4.101.2 (Translation - Spanish)

### ISSUE THREAD

**Issue by Corsair-63** [rgleason/watchdog_pi#81]
The display of translation has been improved but still some messages are not ready for translation, because they are translated in Crowdin file.
Today I've done a double check of translations file and only I had to do a minor touch-up of 4 to 5 strings, but some of them yet translated are not displayed in the plugin.

in the next few days, I'll check on board if some of the previous issues have been already fixed, I'll revert on findings.

attached example screenshots of missing translations.
![sshot-2](https://github.com/rgleason/watchdog_pi/assets/76228638/cea77516-20c5-4900-a7fb-cad5652fc6ff)
![sshot-4](https://github.com/rgleason/watchdog_pi/assets/76228638/b4d0de8c-9288-4758-9290-11013a47d2c8)
![sshot-5](https://github.com/rgleason/watchdog_pi/assets/76228638/f823a26a-be2e-4a05-b9ce-0bce337a16d7)
![sshot-6](https://github.com/rgleason/watchdog_pi/assets/76228638/833d32f3-d1e9-46ec-9b72-0eccfbcdbaa4)

**Comment by Corsair-63** [comment]
As far as I see with latest version of plugin 2.4.103 in Windows all string are translated as per Crowdin file

**Comment by rgleason** [comment]
Thanks Corsair
