### ISSUE TITLE
Bug: Continuously repeating alarm causes O crash

### ISSUE THREAD

**Issue by rgleason** [rgleason/watchdog_pi#91]
Werner reports:

> One other thing … 2 nights ago I set the alarm on the AWS. That worked. When it sounded, my crew struggled to get it off. One finally just switched off the sound of the (windows) pc. Clever! A few hours later .. OpenCPN crashed. And quite some settings were gone, had to reinstall plugins, whereas the dashboards were still there.
> 
> So, my thoughts here: if WD generates a repeating alarm (endlessly) it can cause a crash. I do have the the crash log, if that is of any help.
> 
>

**Comment by rgleason** [comment]
Werner has provided two files which are uploaded here:

[1.nmea.txt](https://github.com/rgleason/watchdog_pi/files/13891142/1.nmea.txt)
[2.nmea.txt](https://github.com/rgleason/watchdog_pi/files/13891143/2.nmea.txt)

**Comment by bdbcat** [comment]
Sounds like a transient bug.  Impossible to trace.
If not repeatable, suggest close this pending further reports.

**Comment by rgleason** [comment]
Closing as suspect transient.  Please reopen if it occurs again
